### ISSUE TITLE
Error in GetType(void) 

### ISSUE THREAD

**Issue by AFP33** [yardenshafir/PoolViewer#6]
When i trying to use the PoolData I have error in function GetType(void) for accessing `_RTLP_HP_HEAP_GLOBALS`, it's say:
`E_NOINTERFACE No such interface supported`.

**Comment by yardenshafir** [comment]
Sounds like you are loading the incorrect dbghelp.dll/dbgeng.dll. Can you make sure you are loading the ones from the SDK path (`c:\Program Files (x86)\Windows Kits\10\Debuggers\x64`) and not the ones from `system32`? The System32 ones are broken and won't fetch symbols correctly.
You can either copy the DLLs from the SDK into the same directory where you downloaded/built PoolViewer.exe, or you can configure the search path in the app.

**Comment by AFP33** [comment]
thank you for your respond. I try to load your `dbghelp.dll/dbgeng.dll` in `Binaries` folder and it's doesn't work correctly, so I change the `dlls` path to SDK path you mentioned. it's work.

**Comment by yardenshafir** [comment]
Perfect, thanks for testing! The DLLs under `Binaries` might be out of date... I'll remove them to avoid future confusion.
